### ISSUE TITLE
exercise 11 https://github.com/Abdul-Azeez/javascriprepo/tree/master/ParentChild

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/javascriprepo#11]
https://github.com/Abdul-Azeez/javascriprepo/tree/master/ParentChild

Create a div with height 100 and scroll bars. Display a list of checkbox color, drinks, movies and bikes in this div. Now when you click on color checkbox it should display four checkboxes(red, yellow, green, blue) as a child list and color checkbox should be checked with its child list of checkboxes. Again when you click on color checkbox child list should be hidden and its child checkboxes should get deselected(clear state). Same with movies, drink and bikes.movies: [Dar, Sir]drinks: [coke, pepsi, dew]bikes: [V-rod, pulsar, cbz]Remember: When you click on a parent checkbox and if child list checkboxes are out of visible area the div's scrollbars should scroll and child list should be visible automatically. We should not scroll the div to see them(child list of checkboxes).

**Comment by yuktikhurana** [comment]
1. for css... when you want to share css among elements, please use a class. Id is for a unique element.
2. Variable naming is not appropriate. Should not start with an uppercase(e.g. Elements)
3. Do not hardcode numbers like 10.(used in scrollTop expression)

**Comment by Abdul-Azeez** [comment]
Done. Please Check

**Comment by yuktikhurana** [comment]
1. css issue still not resolved. Please go through class and id once. Can we replace this ( .colorTick, .moviesTick, .drinksTick, .bikesTick) with a single class ? yes/no? why/why not ? Do let me know the answer.
2. Naming issues
3. 10 is still hardcoded. Try to find some replacement maybe for scroll top.
   feel free to discuss.

**Comment by Abdul-Azeez** [comment]
Done

**Comment by yuktikhurana** [comment]
1. I think we're not using this https://github.com/Abdul-Azeez/javascriprepo/blob/master/ParentChild/parentchild.js#L12 . Please remove this and also the console.log statement
   2.can we use a better name https://github.com/Abdul-Azeez/javascriprepo/blob/master/ParentChild/parentchild.js#L9 tChid ?
2. https://github.com/Abdul-Azeez/javascriprepo/blob/master/ParentChild/parentchild.js#L20
   instead of childNodes let's target only checkboxes.

**Comment by Abdul-Azeez** [comment]
Done

**Comment by yuktikhurana** [comment]
looks good
