### ISSUE TITLE
exercise 12 https://github.com/Abdul-Azeez/javascriprepo/tree/master/adddeletetable

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/javascriprepo#12]
https://github.com/Abdul-Azeez/javascriprepo/tree/master/adddeletetable

```
Create a tableWhen you click on 'Add new row' button:
It should add a new row in the table.
In the name and email column there will a textfield.
In the action column there will be a button save.
```

When you enter some value in textfields and click save, then:

```
Values will be saved(if valid). i.e. Name should be present, Email should be a valid email.
Textfields will be replaced by the values entered.
Save button will be replace by edit / delete links.
```

**Comment by mkangia** [comment]
Not able to edit an added row.
Please modularise the code. The methods are huge.

Please resubmit

**Comment by Abdul-Azeez** [comment]
Done

**Comment by mkangia** [comment]
It seems to be working well now. Please add checks for email and name to be valid and modularise the code.

**Comment by Abdul-Azeez** [comment]
Done.

**Comment by mkangia** [comment]
Checks working well. Still missing improvement in code quality.

**Comment by Abdul-Azeez** [comment]
Please Check.
